In [12]:
import numpy as np
import matplotlib.pyplot as plt


In [13]:
data = np.genfromtxt('Delivery.csv', delimiter=',')
print(data)

x_data = data[:,:-1]
y_data = data[:,-1]
print(x_data)
print(y_data)



[[ 100.     4.     9.3]
 [  50.     3.     4.8]
 [ 100.     4.     8.9]
 [ 100.     2.     6.5]
 [  50.     2.     4.2]
 [  80.     2.     6.2]
 [  75.     3.     7.4]
 [  65.     4.     6. ]
 [  90.     3.     7.6]
 [  90.     2.     6.1]]
[[ 100.    4.]
 [  50.    3.]
 [ 100.    4.]
 [ 100.    2.]
 [  50.    2.]
 [  80.    2.]
 [  75.    3.]
 [  65.    4.]
 [  90.    3.]
 [  90.    2.]]
[ 9.3  4.8  8.9  6.5  4.2  6.2  7.4  6.   7.6  6.1]


In [14]:
lr = 0.0001
theta0 = 0
theta1 = 0
theta2 = 0

epoches = 1000


def computer_error(theta0, theta1, theta2, x_data, y_data):
    total_error = 0
    for i in range(0, len(x_data)):
        total_error += (y_data[i] - (theta0 + theta1 * x_data[i,0]+theta2*x_data[i,1])) ** 2
        
    return total_error / float(len(x_data))


def gradient_descent_runner(x_data, y_data, theta0, theta1, theta2,lr, epoches):
     m = float(len(x_data))
     
     for i in range(epoches):
         theta0_grad = 0
         theta1_grad = 0
         theta2_grad = 0
         
         for j in range(0, len(x_data)):
             theta0_grad += (1/m) * ((theta1 * x_data[j,0] + theta2 * x_data[j,1] + theta0) - y_data[j])
             theta1_grad += (1/m) * x_data[j,0] * ((theta1 * x_data[j,0] + theta2 * x_data[j,1] + theta0) - y_data[j])
             theta2_grad += (1/m) * x_data[j,1] * ((theta1 * x_data[j,0] + theta2 * x_data[j,1] + theta0) - y_data[j])
             
         # 更新 bk
         theta0 = theta0 - lr * theta0_grad
         theta1 = theta1 - lr * theta1_grad
         theta2 = theta2 - lr * theta2_grad
         
     return theta0, theta1, theta2

print("starting theta0 = {0}, theta1 = {1}, theta2 = {2}, error = {3}".format(theta0, theta1, theta2, computer_error(theta0, theta1, theta2, x_data, y_data)))
print("running....")

theta0, theta1, theta2 = gradient_descent_runner(x_data, y_data, theta0, theta1, theta2, lr, epoches)
print("after {0} iterations theta0 = {1}, theta1 = {2}, theta2 = {3}, error = {4}".format(epoches, theta0, theta1, theta2, computer_error(theta0, theta1, theta2, x_data, y_data)))



starting theta0 = 0, theta1 = 0, theta2 = 0, error = 47.279999999999994
running....
after 1000 iterations theta0 = 0.006971416196678632, theta1 = 0.08021042690771771, theta2 = 0.07611036240566814, error = 0.7731271432218118
