In [1]:
import numpy as np

#输入数据
X = np.array([[1,0,0],
              [1,0,1],
              [1,1,0],
              [1,1,1]])
Y = np.array([[0,1,1,0]])

# 权值初始化
V = np.random.random((3,4))*2-1
W = np.random.random((4,1))*2-1
print(V)
print(W)

# 学习率
lr = 0.11

def sigmoid(x):
    return 1.0/(1+np.exp(-x))

def dsigmoid(x):
    return x*(1-x)

def update():
    global X,Y,W,V,lr
    
    L1 = sigmoid(np.dot(X,V))
    L2 = sigmoid(np.dot(L1,W))
    
    L2_delta = (Y.T - L2)*dsigmoid(L2)
    L1_delta = L2_delta.dot(W.T)*dsigmoid(L1)
    
    W_C = lr * L1.T.dot(L2_delta)
    V_C = lr * X.T.dot(L1_delta)
    
    W = W + W_C
    V = V + V_C
    
    

[[ 0.398407   -0.39354398  0.96303652  0.98738656]
 [-0.91705192  0.11164073 -0.19437163  0.08421695]
 [-0.6828816   0.54006443 -0.12582656  0.20140819]]
[[ 0.63804254]
 [ 0.89773456]
 [-0.82049772]
 [ 0.92379203]]


In [2]:
for i in range(20000):
    update()
    if i%500 == 0:
        L1 = sigmoid(np.dot(X,V))
        L2 = sigmoid(np.dot(L1,W))
        
        print('error: ', np.mean(np.abs(Y.T-L2)))


L1 = sigmoid(np.dot(X,V))
L2 = sigmoid(np.dot(L1,W))
print(L2)

error:  0.5010484989
error:  0.500088442715
error:  0.499446224766
error:  0.497735463454
error:  0.490885263955
error:  0.460783726406
error:  0.361676661424
error:  0.217866490313
error:  0.146217473751
error:  0.112235012182
error:  0.0928377854986
error:  0.0802368011117
error:  0.0713265178661
error:  0.0646475985832
error:  0.0594257250217
error:  0.0552114168301
error:  0.0517252896187
error:  0.048784136454
error:  0.0462625481698
error:  0.0440716077809
error:  0.0421463981111
error:  0.0404383357936
error:  0.0389102825769
error:  0.0375333234933
error:  0.0362845822719
error:  0.035145702796
error:  0.0341017701839
error:  0.0331405291909
error:  0.0322518080914
error:  0.0314270873492
error:  0.0306591721104
error:  0.0299419403279
error:  0.0292701467808
error:  0.0286392689492
error:  0.0280453846107
error:  0.027485073746
error:  0.026955339267
error:  0.0264535424557
error:  0.0259773500035
error:  0.0255246902735
[[ 0.02007129]
 [ 0.97477554]
 [ 0.97405347]
 [ 0.029135